package game.entity;
// Generated 23/07/2018 09:12:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer pkCodEvent;
     private String nome;
     private String horario;
     private String dataEvent;
     private String sala;
     private String palestrante;
     private String tipo;
     private Set RUsuarioEventos = new HashSet(0);

    public Evento() {
    }

     public Evento(Integer pkCodEvent) {
        this.pkCodEvent = pkCodEvent;
    }
    
    public Evento(Integer pkCodEvent, String nome, String horario, String dataEvent, String sala, String palestrante, String tipo) {
        this.pkCodEvent = pkCodEvent;
        this.nome = nome;
        this.horario = horario;
        this.dataEvent = dataEvent;
        this.sala = sala;
        this.palestrante = palestrante;
        this.tipo = tipo;
    }
    
    public Evento(String nome, String horario, String dataEvent, String sala, String palestrante, String tipo, Set RUsuarioEventos) {
       this.nome = nome;
       this.horario = horario;
       this.dataEvent = dataEvent;
       this.sala = sala;
       this.palestrante = palestrante;
       this.tipo = tipo;
       this.RUsuarioEventos = RUsuarioEventos;
    }
   
    public Integer getPkCodEvent() {
        return this.pkCodEvent;
    }
    
    public void setPkCodEvent(Integer pkCodEvent) {
        this.pkCodEvent = pkCodEvent;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getDataEvent() {
        return this.dataEvent;
    }
    
    public void setDataEvent(String dataEvent) {
        this.dataEvent = dataEvent;
    }
    public String getSala() {
        return this.sala;
    }
    
    public void setSala(String sala) {
        this.sala = sala;
    }
    public String getPalestrante() {
        return this.palestrante;
    }
    
    public void setPalestrante(String palestrante) {
        this.palestrante = palestrante;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getRUsuarioEventos() {
        return this.RUsuarioEventos;
    }
    
    public void setRUsuarioEventos(Set RUsuarioEventos) {
        this.RUsuarioEventos = RUsuarioEventos;
    }
    
     @Override
    public String toString(){
        return getNome();
    }
}


