package game.entity;
// Generated 23/07/2018 09:12:30 by Hibernate Tools 4.3.1



/**
 * RUsuarioEvento generated by hbm2java
 */
public class RUsuarioEvento  implements java.io.Serializable {


     private RUsuarioEventoId id;
     private Evento evento;
     private Usuario usuario;
     private int presenca;

    public RUsuarioEvento() {
    }

    public RUsuarioEvento(RUsuarioEventoId id, Evento evento, Usuario usuario, int presenca) {
       this.id = id;
       this.evento = evento;
       this.usuario = usuario;
       this.presenca = presenca;
    }
   
    public RUsuarioEventoId getId() {
        return this.id;
    }
    
    public void setId(RUsuarioEventoId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getPresenca() {
        return this.presenca;
    }
    
    public void setPresenca(int presenca) {
        this.presenca = presenca;
    }




}


