package game.entity;
// Generated 23/07/2018 09:12:30 by Hibernate Tools 4.3.1



/**
 * RUsuarioEventoId generated by hbm2java
 */
public class RUsuarioEventoId  implements java.io.Serializable {


     private String fkCpf;
     private int fkCodEvent;

    public RUsuarioEventoId() {
    }

    public RUsuarioEventoId(String fkCpf, int fkCodEvent) {
       this.fkCpf = fkCpf;
       this.fkCodEvent = fkCodEvent;
    }
   
    public String getFkCpf() {
        return this.fkCpf;
    }
    
    public void setFkCpf(String fkCpf) {
        this.fkCpf = fkCpf;
    }
    public int getFkCodEvent() {
        return this.fkCodEvent;
    }
    
    public void setFkCodEvent(int fkCodEvent) {
        this.fkCodEvent = fkCodEvent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RUsuarioEventoId) ) return false;
		 RUsuarioEventoId castOther = ( RUsuarioEventoId ) other; 
         
		 return ( (this.getFkCpf()==castOther.getFkCpf()) || ( this.getFkCpf()!=null && castOther.getFkCpf()!=null && this.getFkCpf().equals(castOther.getFkCpf()) ) )
 && (this.getFkCodEvent()==castOther.getFkCodEvent());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFkCpf() == null ? 0 : this.getFkCpf().hashCode() );
         result = 37 * result + this.getFkCodEvent();
         return result;
   }   


}


