package game.entity;
// Generated 23/07/2018 09:12:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String pkCpf;
     private String nome;
     private String email;
     private String senha;
     private String telefone;
     private String endereco;
     private String curso;
     private String instituicao;
     private String dataNasc;
     private Set RUsuarioEventos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String pkCpf, String nome, String email, String senha, String endereco, String dataNasc) {
        this.pkCpf = pkCpf;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.endereco = endereco;
        this.dataNasc = dataNasc;
    }
    public Usuario(String pkCpf, String nome, String email, String senha, String telefone, String endereco, String curso, String instituicao, String dataNasc, Set RUsuarioEventos) {
       this.pkCpf = pkCpf;
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.telefone = telefone;
       this.endereco = endereco;
       this.curso = curso;
       this.instituicao = instituicao;
       this.dataNasc = dataNasc;
       this.RUsuarioEventos = RUsuarioEventos;
    }
   
    public String getPkCpf() {
        return this.pkCpf;
    }
    
    public void setPkCpf(String pkCpf) {
        this.pkCpf = pkCpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }
    public String getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(String dataNasc) {
        this.dataNasc = dataNasc;
    }
    public Set getRUsuarioEventos() {
        return this.RUsuarioEventos;
    }
    
    public void setRUsuarioEventos(Set RUsuarioEventos) {
        this.RUsuarioEventos = RUsuarioEventos;
    }




}


